import dynamic from "next/dynamic";
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import Button from "@components/ui/button";
import Navbar from "@components/layout/navbar/navbar";
import ErrorMessage from "@components/ui/error-message";
import renderProductCard from "@components/product/render-product-card";
import NotFound from "@components/common/not-found";
import { useProductsQuery } from "@data/product/use-products.query";
import { Fragment } from "react";
import { useTranslation } from "next-i18next";
import Footer from "@components/common/footer";
import Image from 'next/image';
import Card from "@components/ui/card";



const ProductFeedLoader = dynamic(
  () => import("@components/ui/loaders/product-feed-loader")
);

const SideBar = dynamic(
  () => import("@components/ui/sidebar-menu")
);

const Feed = () => {
  const { t } = useTranslation("common");
  const { query } = useRouter();
  const {
    isFetching: loading,
    isFetchingNextPage: loadingMore,
    fetchNextPage,
    hasNextPage,
    isError,
    data,
    error,
  } = useProductsQuery({
    type: query.type as string,
    text: query?.text as string,
    category: query?.category as string,
  });

  if (isError && error) return <ErrorMessage message={error.message} />;
  function handleLoadMore() {
    fetchNextPage();
  }
  if (!loading && !data?.pages?.[0]?.data?.length) {
    return (
      <div className="bg-gray-100 min-h-full pt-6 pb-8 px-4 lg:p-8">
        <NotFound text="text-not-found" className="w-7/12 mx-auto" />
      </div>
    );
  }
  return (
    <>
     <Navbar />
    {/* sidebar */}

    <div className="w-full bg-light-100">
      <div className="flex flex-col md:flex-row max-w-7xl w-full mx-auto py-10 px-5 xl:py-14 xl:px-8 2xl:px-14">
        
        {/* Contact form */}
        <div className="w-full order-1 md:order-2 mb-8 md:mb-0 md:ms-7 lg:ms-9 p-5 md:p-8 bg-light">
          {/* <h1 className="mb-7 text-xl md:text-2xl font-body font-bold text-accent">
           
          </h1> */}

            {/* <img
              src="/logo1.png"
              alt={t("nav-menu-contact")}
              className="w-full h-auto"
            /> */}
            
            
            <section className="py-8 px-4 lg:py-10 lg7px-8 xl:py-14 xl:px-16 2xl:px-20 text-left mb-8">

                    <p className="py-4 text-gray-500">This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                    <p className="py-4 text-gray-500">Please read the following terms and conditions very carefully as your use of service is subject to your acceptance of and compliance with the following terms and conditions</p>
                    <p className="py-4 text-gray-500"><strong>General Information</strong></p>
                    <p className="py-4 text-gray-500">The domain name www.baptismdressindia.com (hereinafter referred to as “Website”) is registered in the name of Navin Creations a company incorporated under the Companies Act.</p>
                    <p className="py-4 text-gray-500">Your use of the Website and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Website. If you transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction.</p>
                    <p className="py-4 text-gray-500">For the purpose of these Terms of Use, wherever the context so requires “You” or “User” shall mean any natural or legal person who has agreed to become a member of the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. Navin Creations allows User to surf the Website or making purchases without registering on the Website. The term “we”, “us”, “our” shall mean Navin Creations or baptismdressindia.com or all.</p>
                    <p className="py-4 text-gray-500">ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING.</p>
                    <p className="py-4 text-gray-500">All products/services and information displayed on baptismdressindia.com constitute an “invitation to offer”. Your order for purchase constitutes your “offer” which shall be subject to the terms and conditions as listed below. baptismdressindia.com reserves the right to accept or reject your offer. If you have supplied us with your valid email address, we will notify you by email as soon as possible to confirm receipt of your order and email you again to confirm details and therefore process the order. Our acceptance of your order will take place upon dispatch of the product(s) ordered. No act or omission of baptismdressindia.com prior to the actual dispatch of the product(s) ordered will constitute acceptance of your offer.</p>
                    <p className="py-4 text-gray-500"><strong>Membership Eligibility</strong></p>
                    <p className="py-4 text-gray-500">Use of the Site is available only to persons who can form legally binding contracts under applicable law. Persons who are “incompetent to contract” within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Site. You may use this site only if your age is over 18 years.</p>
                    <p className="py-4 text-gray-500">baptismdressindia.com reserves the right to terminate your membership and refuse to provide you with access to the Site if baptismdressindia.com discovers that you are under the age of 18 years. In case of a business entity, you represent that you have the necessary authority to bind the entity to this User Agreement. Unless otherwise specified, the materials on this website are directed solely at those who access this website from India. baptismdressindia.com makes no representation that any products or services referred to in the materials on this website are appropriate for use, or available outside India. Those who choose to access this Site from outside India are responsible for compliance with local laws if and to the extent local laws are applicable. baptismdressindia.com will deliver the products only within India and will not be liable for any claims relating to any products ordered from outside India.</p>
                    <p className="py-4 text-gray-500">Unless otherwise stated as additional terms and conditions which are product specific, these terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order submitted. By using the services of baptismdressindia.com you agree to be bound by the Terms and Conditions.
Modifications</p>
                    <p className="py-4 text-gray-500">baptismdressindia.com reserves the right at all times to discontinue or modify the Terms of Use and/or our Privacy Policy as we deem necessary or desirable without any prior notification. Such changes may include, among other things, the adding of certain fees and charges. Any such modifications would be effective immediately. We suggest that you read our Terms and Conditions and Privacy policy from time to time to stay informed. Any use of the site after such modifications would be deemed to constitute acceptance of the modified terms by the End User.</p>
                    <p className="py-4 text-gray-500"><strong>Account and Registration</strong></p>
                    <p className="py-4 text-gray-500">It is the user’s responsibility to keep the details of the account and password confidential and you agree to accept responsibility for all activities that occur under Your Account or Password. baptismdressindia.com shall not be liable to any person for any loss or damage which may arise as a result of any failure by the user to protect the account details or the password. In case of any suspected breach please contact us immediately. If baptismdressindia.com has reason to believe that there is likely to be a breach of security or misuse of the baptismdressindia.com Site, we may require you to change your password or we may suspend your account without any liability to baptismdressindia.com.</p>
                    <p className="py-4 text-gray-500"><strong>You also agree to:</strong></p>
                    <p className="py-3 text-gray-500">1. Provide true, accurate, current and complete information about yourself as prompted by baptismdressindia.com website during the registration process (such information being the “Registration Data”)</p>
                    <p className="py-3 text-gray-500">2. Maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, incomplete, or not current or if baptismdressindia.com has reasonable grounds to suspect that such information is untrue, inaccurate, not current or not in accordance with the User Agreement, baptismdressindia.com will have the right to indefinitely suspend or terminate your membership and refuse to provide you with access to the Site.</p>
                    <p className="py-4 text-gray-500"><strong>Pricing, Promotions & Coupon Codes</strong></p>
                    <p className="py-4 text-gray-500"><strong>Pricing Information</strong></p>
                    <p className="py-4 text-gray-500">While baptismdressindia.com shall endeavour to provide accurate product and pricing information, yet typographical errors might occur. baptismdressindia.com cannot confirm the price of a product until after you order. In the event that a product is listed at an incorrect price or with incorrect information due to an error in pricing or product information, baptismdressindia.com shall have the right, at our sole discretion, to refuse or cancel any orders placed for that product, unless the product has already been dispatched. In the event that an item is mis-priced, baptismdressindia.com may, at its discretion, either contact you for instructions or cancel your order and notify you of such cancellation. Unless the product ordered by you has been dispatched, your offer will not be deemed accepted and baptismdressindia.com will have the right to modify the price of the product and contact you for further instructions using the e-mail address provided by you during the time of registration, or cancel the order and notify you of such cancellation. In the event that baptismdressindia.com accepts your order the same shall be debited to your credit card account and duly notified to you by email that the payment has been processed. The payment may be processed prior to baptismdressindia.com dispatch of the product that you have ordered. If we have to cancel the order after we have processed the payment, the said amount will be reversed back to your credit card account.</p>
                    <p className="py-4 text-gray-500"><strong>Promotion Offers</strong></p>
                    <p className="py-4 text-gray-500">For any returned or undelivered orders, partial or whole, the user will not be eligible to avail of the offer used to purchase the original order. The benefit of the offer would also not be included in the refund provided. If the product(s) returned are part of any free offer, Eg: Buy 2 get 1 free or Buy 1 get 1 free, all the products related to the offer would have to be returned by you, as they have been purchased as part of a group offer. The refund/replacement process would only be initiated once all the products have been returned.</p>
                    <p className="py-4 text-gray-500">From time to time, we may provide a free sample or gift along with our orders which are eligible for the offer. These samples/gifts will not be eligible for return/replacement/refund under any circumstances.</p>
                    <p className="py-4 text-gray-500"><strong>Coupon Codes & Cart Offers</strong></p>
                    <p className="py-4 text-gray-500">To offer special discounts to our users from time to time, we share coupon codes based discounts. To prevent any possible misuses we have put in place a few checks on the ways in which these coupon codes can be used.</p>
                    <p className="py-4 text-gray-500">To make the best use of the coupon code offers, please go through the following terms and conditions applicable on all coupon codes</p>
                    <p className="py-4 text-gray-500">1. Coupon Codes & Cart Offers based offer will be valid upon application of the coupon code at the time of placing order.</p>
                    <p className="py-4 text-gray-500">2. Coupon Codes & Cart Offers will be valid till the date communicated or till stocks last on the applicable products, whichever happens earlier.</p>
                    <p className="py-4 text-gray-500">3. A Coupon Codes & Cart Offers cannot be clubbed with any other coupon code or with any other offer including offers running on the site without using coupons.</p>
                    <p className="py-4 text-gray-500">5. Coupon codes shared individually with a user will be applicable on purchase made by that particular user only.</p>
                    <p className="py-4 text-gray-500">6. The website reserves the right to change the terms and conditions of any coupon code any time without prior intimation.</p>
                    <p className="py-4 text-gray-500">7. Shipping / Cash on delivery rules and charges apply on the net amount payable upon application of the coupon code unless otherwise mentioned.</p>
                    <p className="py-4 text-gray-500">8. Cashback coupons are valid for next purchase as per the conditions mentioned with the Cashback offer.</p>
                    <p className="py-4 text-gray-500">9. The Cash Coupons added to an account can be changed/updated at any point of time by Navin Creations. without any prior intimation. These changes could be made from time to time even before the valid expiry date of the existing Cash Coupons.</p>
                    <p className="py-4 text-gray-500"><strong>Credit Card Details</strong></p>
                    <p className="py-4 text-gray-500">You hereby agree, understand and confirm that the credit card details provided by you for availing of services on website will be correct, accurate and current. Under no circumstances you shall use a credit card which is not lawfully owned by you. You further agree and undertake to provide the correct and valid credit card details to us. The card details will not be utilised and shared by us with any of the third parties unless required for fraud verifications or by law, regulation or court order. We will not be liable for any credit card fraud. The liability for use of a card fraudulently will be on you and the onus to ‘prove it otherwise’ shall be exclusively on you.</p>
                    <p className="py-4 text-gray-500"><strong>Fraudulent /Declined Transactions</strong></p>
                    <p className="py-4 text-gray-500">In case of fraudulent use of the site, we reserve the right to recover the cost of goods, collection charges and lawyers fees from person(s) concerned. We reserve the right to initiate legal proceedings against such person(s) for fraudulent use of the Site and any other unlawful acts or acts or omissions in breach of these terms and conditions.</p>
                    <p className="py-4 text-gray-500"><strong>Cancellations by the customer</strong></p>
                    <p className="py-4 text-gray-500">In case we receive a cancellation notice and the order has not been shipped by us, we shall cancel the order and refund the entire amount. The orders that have already been shipped out by us will not be cancelled and you will have to check our return policy on those orders.</p>
                    <p className="py-4 text-gray-500"><strong>Cancellation by baptismdressindia.com</strong></p>
                    <p className="py-4 text-gray-500">Under certain circumstances it might not be possible for us to accept an order and we may be compelled to cancel the same. We reserve the right to refuse or cancel any order for any reason at our sole discretion. Some situations that may result in your order being cancelled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also ask for additional verifications or information before accepting any order. We will contact you if all or any portion of your order is cancelled or if additional information is required to accept your order. If your order is cancelled after your credit card has been charged, the said amount will be reversed back in your Card Account. The customer agrees not to dispute the decision made by us and accept our decision regarding the cancellation.</p>
                    <p className="py-4 text-gray-500"><strong>Payment</strong></p>
                    <p className="py-4 text-gray-500">While availing any of the payment method/s offered by us, we are not responsible or take no liability of whatsoever nature in respect of any loss or damage arising directly or indirectly to you out of the decline due to:</p>
                    <p className="py-4 text-gray-500">1. lack of authorization for any transaction/s,</p>
                    <p className="py-4 text-gray-500">2. or exceeding the preset limit mutually agreed by you and between your “Bank/s”,</p>
                    <p className="py-4 text-gray-500">3. or any payment issues arising out of the transaction,</p>
                    <p className="py-4 text-gray-500">4. or decline of transaction for any other reason/s.</p>
                    <p className="py-4 text-gray-500">All payments made against the purchases/services on baptismdressindia.com by you shall be compulsorily in Indian Rupees acceptable by the Union of India. baptismdressindia.com does not accept any other form of currency with respect to the purchases.</p>
                    <p className="py-4 text-gray-500">Before shipping your order to you, we may request you to provide supporting documents (including but not limited to Govt. issued ID and address proof) to establish the ownership of the payment instrument used by you for your purchase. This is done in the interest of providing a safe online shopping environment to our users.</p>
                  
                    <p className="py-4 text-gray-500"><strong>Guidelines for Writing Product Reviews</strong></p>
                    <p className="py-4 text-gray-500"><strong>Who can write a product review on baptismdressindia.com?</strong></p>

                    <p className="py-4 text-gray-500">Anyone who has an account with baptismdressindia.com can write a product review.</p>
                    <p className="py-4 text-gray-500">Are there any specific rules that need to be followed while writing a review?</p>
                    <p className="py-4 text-gray-500">No, there are no specific rules which need to be followed while writing a review. However we have we put together some guidelines which can be followed while writing a product review –</p>

                    <p className="py-4 text-gray-500">1. Be Precise and Specific
<br></br>While writing a product review you should keep in mind the fact that other Navin Creations users might use your review to form a judgment, whether to select the product or not. Therefore a precise, specific & unbiased product review plays a critical part and would always help a customer make a better choice about which product to buy.</p>
                    <p className="py-4 text-gray-500">2. Don’t keep any loose ends<br></br>Always keep all the details provided well settled and explained. Incomplete or inaccurate information will not help any customer other than confusing them about the product.</p>
                    <p className="py-4 text-gray-500">3. Spell what is required<br></br>A good review should serve the most basic purpose i.e. what you liked/disliked about the product and why with the exact details.</p>
                    <p className="py-4 text-gray-500">4. Remove distractions from review<br></br>Before submitting the review for moderation it is wise to spell check and proofread your review accurately.</p>
                    <p className="py-4 text-gray-500"><strong>What needs to be avoided while writing a review?</strong></p>
                    <p className="py-4 text-gray-500">Navin Creations reserves the right to not include the product review that include any one or more of the following –</p>
                    <p className="py-4 text-gray-500">1. Inappropriate content – like promotional information or phone numbers.</p>
                    <p className="py-4 text-gray-500">2. Information not related to product – Shipment/Delivery Experience, availability, ordering etc</p>
                    <p className="py-4 text-gray-500">3. Inaccuracies in product information & product catalogue.</p>
                    <p className="py-4 text-gray-500">4. References – to other retailers, pricing, personal information etc.</p>
                    <p className="py-4 text-gray-500">5. Copying and pasting text from other reviews, guides, or sources.</p>
                    <p className="py-4 text-gray-500">6. Comments on other reviews posted on the product page.</p>
                    <p className="py-4 text-gray-500">7. Foreign language content.</p>
                    <p className="py-4 text-gray-500">8. Off-topic information or obscene content.</p>
                    <p className="py-4 text-gray-500">9. Irrelevant user IDs or email ids used for posting reviews.</p>
                    <p className="py-4 text-gray-500"><strong>User Conduct You Agree and Confirm</strong></p>
                    <p className="py-4 text-gray-500">1. That you will use the services provided by baptismdressindia.com, its affiliates, consultants and contracted companies, for lawful purposes only and comply with all applicable laws and regulations while using the Site and transacting on the Site.</p>
                    <p className="py-4 text-gray-500">2. You will provide true, accurate, complete and current information in all instances where such information is requested of you. baptismdressindia.com reserves the right to confirm and validate the information and other details provided by you at any point of time. If upon confirmation your details are found not to be true (wholly or partly), baptismdressindia.com has the right in its sole discretion to reject the registration and debar you from using the Services of baptismdressindia.com and / or other affiliated websites without prior intimation whatsoever.</p>
                    <p className="py-4 text-gray-500">3. To compensate baptismdressindia.com for any extra cost incurred for redelivery in the event of a non-delivery in the first instance on account of a mistake by you (i.e. wrong name or address or any other wrong information).</p>
                    <p className="py-4 text-gray-500">4. That you using your best and prudent judgment before entering into any transaction through this Site doing so at your sole risk.</p>
                    <p className="py-4 text-gray-500">5. After placing an order for a product you agree to be bound by the conditions of sale included in the item’s description.</p>
                    <p className="py-4 text-gray-500">You may not use the Site for any of the following purposes:</p>
                    <p className="py-4 text-gray-500">1. Disseminating any unlawful, harassing, libellous, abusive, threatening, harmful, vulgar, obscene, or otherwise objectionable material.</p>
                    <p className="py-4 text-gray-500">2. Transmitting material that encourages conduct that results in civil liability or otherwise breaches any relevant laws, regulations or code of practice or constitutes a criminal offence.</p>
                    <p className="py-4 text-gray-500">3. Gaining unauthorised access to other computer systems.</p>
                    <p className="py-4 text-gray-500">4. Interfering with any other person’s use or enjoyment of the Site.</p>
                    <p className="py-4 text-gray-500">5. Breaching any applicable laws.</p>
                    <p className="py-4 text-gray-500">6. Interfering or disrupting networks or web sites connected to the Site.</p>
                    <p className="py-4 text-gray-500">7. Making, transmitting or storing electronic copies of materials protected by copyright without the permission of the owner.</p>
                    <p className="py-4 text-gray-500"><strong>Design details and Colours.</strong></p>
                    <p className="py-4 text-gray-500">We have made every effort to capture high resolution images of our products so that you get a feel of the design details and colours of our products that appear on the Site as accurately as possible. However, what you actually see will depend on your monitor; we cannot guarantee that your monitor’s display of any colour or other details will be accurate.</p>
                    <p className="py-4 text-gray-500"><strong>Electronic Communications</strong></p>
                    <p className="py-4 text-gray-500">When you visit the Site or send emails to us, you are communicating with us electronically. You hereby provide your consent to receive communications from us electronically. We will communicate with you by email or by posting notices on the Site. You hereby agree that all notices, agreements and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>
                    <p className="py-4 text-gray-500"><strong>Modification of Terms & Conditions of Service</strong></p>
                    <p className="py-4 text-gray-500">baptismdressindia.com reserves the right to make changes to our Terms of Use and/or our Privacy Policy (which is incorporated herein by reference) at our sole discretion and you may not be notified. We suggest to you, therefore, that you re-read this important notice containing our Terms of Use and Privacy Policy from time to time in order that you stay informed as to any such changes. You have accepted the Agreement as amended if you continue to use any of baptismdressindia.com’s Services after any amendments are posted on our Website.

</p>
                    <p className="py-4 text-gray-500"><strong>Terms of Use and baptismdressindia.com Privacy Policy.</strong></p>
                    <p className="py-4 text-gray-500"><strong>Other Terms<br></br>Reviews, Feedback, Submissions



</strong></p>
                    <p className="py-4 text-gray-500">End User acknowledges that all discussion for ratings, comments, bulletin board service, chat rooms and/or other message or communication facilities (collectively “Communities”) are public and not private communications. baptismdressindia.com does not control or endorse the content, messages or information found in any Community, and, therefore, baptismdressindia.com specifically disclaims any liability concerning the Communities and any actions resulting from End Users participation in any Community, including any objectionable content. Generally, any communication which End User posts to baptismdressindia.com (whether in chat rooms, discussion groups, message boards or otherwise) is considered to be non-confidential. If particular web pages permit the submission of communications that will be treated by baptismdressindia.com as confidential, that fact will be stated on those pages. By posting comments, messages or other information on the Site, End User grants baptismdressindia.com the right to use such comments, messages or information for promotions, advertising, market research or any other lawful purpose.</p>
                    <p className="py-4 text-gray-500"><strong>Copyright & Trademark</strong></p>


                    <p className="py-4 text-gray-500">Everything located on or in this Site, including the Microsites, is our exclusive property and can be used with express permission of the copyright and/or trademark owner. ANY COPYING, DISTRIBUTING, TRANSMITTING, POSTING, LINKING, DEEP LINKING, OR OTHERWISE MODIFYING OF THIS SITE OR ANY OF THE MICROSITES WITHOUT OUR EXPRESS WRITTEN PERMISSION OF baptismdressindia.com IS STRICTLY PROHIBITED. Any violation of this policy may result in a copyright, trademark or other intellectual property right infringement that may subject End User to civil and / or criminal penalties.</p>
                    <p className="py-4 text-gray-500">This Site and Microsites contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music, sound, and the entire contents of website protected by copyright. We own a copyright in the selection, coordination, arrangement and enhancement of such content, as well as in the content original to it. End User may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit, any of the content, in whole or in part. End User may download / print / save copyrighted material for End User’s personal use only. Except as otherwise expressly stated under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material without our express permission of baptismdressindia.com and the copyright owner is permitted. If copying, redistribution or publication of copyrighted material is permitted, no changes in or deletion of author attribution, trademark legend or copyright notice shall be made. End User acknowledges that he/she/it does not acquire any ownership rights by downloading copyrighted material. Trademarks that are located within or on the Site or a Web site otherwise owned or operated in conjunction with baptismdressindia.com shall not be deemed to be in the public domain but rather the exclusive property of owners, unless such site is under license from the Trademark owner thereof in which case such license is for the exclusive benefit and use of baptismdressindia.com, unless otherwise stated.</p>
                    <p className="py-4 text-gray-500">End User shall not upload, post or otherwise make available on this Site any material protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right. We do not have any express burden or responsibility to provide End User with indications, markings or anything else that may aid End User in determining whether the material in question is copyrighted or trademarked. End User shall be solely liable for any damage resulting from any infringement of copyrights, trademarks, proprietary rights or any other harm resulting from such a submission. By submitting material to any public area of this Site, End User warrants that the owner of such material has expressly granted us the royalty-free, perpetual, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate and distribute such material (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or hereafter developed for the full term of any copyright that may exist in such material. End User also permits any other end user to access, view, store or reproduce the material for that end user’s personal use. End User hereby grants us the right to edit, copy, publish and distribute any material made available on this Site by End User. We hereby reserves the right to terminate its agreement with any End User who repeatedly infringes on copyright rights upon notification to us by the copyright owner.</p>
                    <p className="py-4 text-gray-500">The foregoing provisions of this clause apply equally to and are for the benefit of baptismdressindia.com, its subsidiaries, affiliates and its third party content providers and licensors and each shall have the right to assert and enforce such provisions directly or on its own behalf.</p>
                    <p className="py-4 text-gray-500"><strong>Indemnity</strong></p>
                    <p className="py-4 text-gray-500">You agree to defend, indemnify and hold harmless Navin Creations, its employees, directors, officers, agents and their successors and assigns from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney’s fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to us or any third party including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfillment of any of your obligations under this User Agreement or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of this User Agreement.</p>
                    <p className="py-4 text-gray-500"><strong>Indemnity</strong></p>
                    <p className="py-4 text-gray-500">Termination</p>
                    <p className="py-4 text-gray-500">We may terminate this Agreement at any time. Without limiting the foregoing, we shall have the right to terminate any passwords or accounts of End User in the event of any conduct by End User which we, in our sole discretion, consider to be unacceptable, or in the event of any breach by End User of this Agreement. Our right to any Comments shall survive any termination of this User Agreement. Any such termination of the User Agreement shall not cancel your obligation to pay for the product already ordered from the Site or affect any liability that may have arisen under the User Agreement.</p>
                    <p className="py-4 text-gray-500"><strong>Limitation of Liability and Disclaimers</strong></p>
                    <p className="py-4 text-gray-500">The Site is provided without any warranties or guarantees and in an “As Is” condition. You must bear the risks associated with the use of the Site.</p>
                    <p className="py-4 text-gray-500">The Site provides content from other Internet sites or resources and while we try to ensure that material included on the website is correct, reputable and of high quality, it cannot accept responsibility if this is not the case. We will not be responsible for any errors or omissions or for the results obtained from the use of such information or for any technical problems you may experience with the Site.</p>
                    <p className="py-4 text-gray-500">This disclaimer does not apply to any product warranty offered by the manufacturer of the product as specified in the product specifications. This disclaimer constitutes an essential part of this User Agreement. To the fullest extent permitted under applicable law, we or our suppliers shall not be liable for any indirect, incidental, special, incidental, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses arising out of or in connection with the Site, its services or this User Agreement.</p>
                    <p className="py-4 text-gray-500">Without prejudice to the generality of the section above, the total liability of baptismdressindia.com to you for all liabilities arising out of this User Agreement be it in tort or contract is limited to the value of the product ordered by you. Navin Creations, their associates and technology partners make no representations or warranties about the accuracy, reliability, completeness, currentness and/or timeliness of any content, information, software, text, graphics, links or communications provided on or through the use of the Site or that the operation of the Site will be error free and/or uninterrupted. Consequently, we assume no liability whatsoever for any monetary or other damage suffered by you on account of the delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the Site; and/or any interruption or errors in the operation of the Site.</p>
                    <p className="py-4 text-gray-500"><strong>Site Security</strong></p>
                    <p className="py-4 text-gray-500">You are prohibited from violating or attempting to violate the security of the Site, including, without limitation, (a) accessing data not intended for you or logging onto a server or an account which you are not authorized to access; (b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (c) attempting to interfere with service to any other user, host or network, including, without limitation, via means of submitting a virus to the Site, overloading, “flooding,” “spamming,” “mail bombing” or “crashing;” (d) sending unsolicited email, including promotions and/or advertising of products or services; or (e) forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting. Violations of system or network security may result in civil or criminal liability. baptismdressindia.com will investigate occurrences that may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of this Site or any activity being conducted on this Site. You agree, further, not to use or attempt to use any engine, software, tool, agent or other device or mechanism (including without limitation browsers, spiders, robots, avatars or intelligent agents) to navigate or search this Site other than the search engine and search agents available from baptismdressindia.com on this Site and other than generally available third party web browsers (e.g., Netscape Navigator, Microsoft Explorer).</p>
                    <p className="py-4 text-gray-500"><strong>MISCELLANEOUS</strong></p>
                    <p className="py-4 text-gray-500">1. Force Majeure: Without prejudice to any other provision herein, we will not be liable for any loss, damage or penalty as a result of any delay in or failure to deliver or otherwise perform hereunder due to any cause beyond the our control, including, without limitation, acts of the End User, embargo or other governmental act, regulation or request affecting the conduct of baptismdressindia.com ‘s business, fire, explosion, accident, theft, vandalism, riot, acts of war, strikes or other labor difficulties, lightning, flood, windstorm or other acts of God.</p>
                    <p className="py-4 text-gray-500">2. Entire Agreement: This Agreement and any operating rules for the Website established by baptismdressindia.com constitute the entire agreement of the parties with respect to the subject matter hereof.</p>
                    <p className="py-4 text-gray-500">3. Waiver: No waiver by either party of any breach or default hereunder is a waiver of any preceding or subsequent breach or default. The failure of either party to exercise any of its rights under this Agreement shall not be deemed a waiver or forfeiture of such rights or any other rights provided hereunder.</p>
                    <p className="py-4 text-gray-500">4. Headings: The section headings used herein are for convenience only and shall be of no legal force or effect.</p>
                    <p className="py-4 text-gray-500">5. Severability: If any provision of this Agreement is held invalid by a court of competent jurisdiction, such invalidity shall not affect the enforceability of any other provisions contained in this Agreement and the remaining portions of this Agreement shall continue in full force and effect.</p>
                    <p className="py-4 text-gray-500">6. Governing Law: This Agreement will be governed by laws of India, subject to the Courts in Pune, without reference to conflict of laws principles, if any.</p>
                    <p className="py-4 text-gray-500">7. Payment Decline: We as a merchant shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any Transaction, on Account of the Cardholder having exceeded the preset limit mutually agreed by us with our acquiring bank from time to time.</p>



            </section>

           
          
      
   
          
        </div>
      </div>
    </div>

    <Footer />
        
    </>
  );
};

export default Feed;
